# Site wide configuration

title: Les Bricodeurs
locale: fr_FR
description: "Collectif du num√©rique citoyen"
logo: lesbricodeurs2.png
small-logo: lesbricodeurs-200px.png
url: https://lesbricodeurs.fr
default_locale: "fr"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Les Bricodeurs
  avatar: lesbricodeurs.png
  email: salut@lesbricodeurs.fr
  disqus-shortname: LesBricodeurs
  twitter: LesBricodeurs
  facebook: lesbricodeurs
  github: LesGeeksDuDimanche
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  meetup: fr/Design-et-technologie-pour-projets-citoyens
  slack: enQtMjk4MDg1NTIxMDI4LWU1MjRhMjlmYmYyYmM3MGRhNjg3YjIzMGRiMzk0YjE4OTYyYzUxZWFkMDE1MTZiZTRiOTBhYTA4YTQ5YTA2NTY #invite not limit
  pinterest:
  weibo:
  google:
    plus:
    analytics: UA-64227504-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
